### PR TITLE
Add name fields for the Id Source

### PR DESCRIPTION
**Pull request by ioan-ghisoi-cko**

### CODE REVIEW

**Review by nicolas-maalouf-cko — COMMENTED** [review]
@ioan-ghisoi can you please bump the version to 3.6.0 inside https://github.com/checkout/checkout-sdk-java/blob/dev/gradle.properties ?

**Comment by harry-peirse** [comment]
Hi, thanks for this - @ioan-ghisoi can you remove the two setters though? They will be generated anyway thanks to the lombok libraries so it's just superfluous code at the moment.

**Review by harry-peirse — CHANGES_REQUESTED** [review]
Please remove the setters and their javadoc as these will be autogenerated by lombok.

**Comment by ioan-ghisoi-cko** [comment]
@harry-peirse done. Let me know if anything else is needed.

**Review by harry-peirse — APPROVED** [review]

**Comment by harry-peirse** [comment]
Looks good, thanks

**Pull request merged**
